alias x="exit"
alias vrc="vim ~/.vimrc"
alias ba="vim ~/.bash_aliases"
alias tx="pdflatex"
alias ff="firefox"
alias fm="open . || nautilus ."
alias subl="/Applications/Sublime\ Text.app/Contents/SharedSupport/bin/subl"
alias batt='pmset -g batt'
alias c='cd ~/Documents/Code'
alias n='cd ~/Documents/Notes'
alias makenotes='python ~/Documents/Code/notes/main.py'
