alias x="exit"
alias vrc="vim ~/.vimrc"
alias ba="vim ~/.bash_aliases && source ~/.bash_aliases"
alias ff='find . -name $1'
alias mkcd='mkdir -p $1 && cd $1'
alias tx="pdflatex"
alias batt='pmset -g batt'
alias c='cd ~/Documents/repos'
alias n='cd ~/Documents/Notes'
alias d='cd ~/Desktop'
alias workon='conda activate'
alias deactivate='conda deactivate'
alias vim='nvim'
alias kaexe='killall -r .*.exe'
alias update="sudo pacman -Syu && yay -Syu"
alias ngs='ng serve -o'
alias grep="grep --color=auto"
alias fgrep="fgrep --color=auto"
alias egrep="egrep --color=auto"

# Docker Aliases
alias dps='docker ps'
alias dpsa='docker ps -a'
alias di='docker images'
alias dr='docker run'
alias db='docker build'
alias dex='docker exec -it'
alias drm='docker rm'

# Docker Compose Aliases
alias dcu='docker-compose up'
alias dcd='docker-compose down'
alias dcl='docker-compose logs'
alias dcb='docker-compose build'
alias dcdv='docker-compose down -v'
alias dcwatch='docker compose up --watch'

function gh {
    git clone "https://github.com/$1/$2"
}

function ghme {
    gh "$GITHUB_USERNAME" "$1"
}
