#
# ~/.bashrc
#

# If not running interactively, don't do anything
[[ $- != *i* ]] && return

PS1='[\u@\h \W]\$ '
DEFAULT_PS1=$PS1
PS1='\[\033[31m\][\[\033[33m\]\u\[\033[32m\]@\[\033[34m\]\h \[\033[35m\]\W\[\033[31m\]] \[\033[37m\]\$ '

# Variables
export EDITOR=/usr/bin/nvim
export BROWSER=/usr/bin/google-chrome-stable
export GITHUB_USERNAME=""

# Path
export CustomScriptsPath="$HOME/.scripts:$HOME/.scripts/private:$HOME/.bin"
export NpmPath="$HOME/.npm/bin"
export PATH=$PATH:$CustomScriptsPath:$NpmPath

npm config set prefix "$HOME/.npm"

[[ -f ~/.bash_aliases ]] && . ~/.bash_aliases


if command -v pandoc &> /dev/null; then
    eval "$(pandoc --bash-completion)"
fi

export PATH="$HOME/.local/bin:$PATH"

function gh {
    git clone "git@github.com:$1/$2.git"
}

function ghme {
    gh "$GITHUB_USERNAME" "$1"
}

function docker-bash {
  docker run -it --rm -v ".:/folder" ubuntu /bin/bash
}

function md2pdf {
    md2x.sh "$1" pdf "${@:2}"
}

function md2docx {
    md2x.sh "$1" docx "${@:2}"
}

function md2pptx {
    md2x.sh "$1" pptx "${@:2}"
}

function md2pdf-1in {
    md2pdf "$1" -V "geometry:margin=1in"
}

function md2pdf-beamer {
    md2pdf "$1" -t beamer
}

[[ -f ~/.bashrc_private ]] && . ~/.bashrc_private
